const data = {
  users: [
    {
      _id: 1,
      name: "Sevde",
      email: "svd@example.com",
      password: "123456",
      userGroups: [
        "admin",
        "user",
        "stockController",
        "branchOwner",
        "wareHouse",
        "onlineShopController",
      ],
      favorites: [215632],
    },
    {
      _id: 2,
      name: "Ömer",
      email: "ömer@example.com",
      password: "123456",
      userGroups: [
        "admin",
        "user",
        "stockController",
        "branchOwner",
        "wareHouse",
        "onlineShopController",
      ],
      favorites: [215632],
    },
    {
      _id: 3,
      name: "Bekir",
      email: "bkr@example.com",
      password: "123456",
      userGroups: [
        "admin",
        "user",
        "stockController",
        "branchOwner",
        "wareHouse",
        "onlineShopController",
      ],
      favorites: [215632],
    },
  ],
  products: [
    {
      _id: 1,
      name: "HP Curved Monitor",
      slug: "hp-curved-monitor",
      category: "Monitors",
      image: "/images/monitor1.jpg",
      price: 150,
      countInStock: 10,
      brand: "HP",
      bewertungen: [
        { userId: 1, bewertung: 4 },
        { userId: 2, bewertung: 3 },
      ],
      rating: 3.5,
      numReviews: 43,
      description: "Eye-friendly Monitor",
    },
    {
      _id: 2,
      name: "Microsoft Wireless Keyboard",
      slug: "microsoft-wireless-keyboard",
      category: "Keyboards",
      image: "/images/keyboard1.jpg",
      price: 30,
      countInStock: 20,
      brand: "Microsoft",
      bewertungen: [
        { userId: 1, bewertung: 4 },
        { userId: 2, bewertung: 3 },
      ],
      rating: 2.1,
      numReviews: 7,
      description: "Keyboard without cable",
    },
    {
      _id: 3,
      name: "Thinkpad Laptop",
      slug: "thinkpad-laptop",
      category: "Laptops",
      image: "/images/lenovo-laptop1.jpg",
      price: 750,
      countInStock: 1,
      brand: "Lenovo",
      bewertungen: [
        { userId: 1, bewertung: 4 },
        { userId: 2, bewertung: 3 },
      ],
      rating: 2.4,
      numReviews: 1,
      description: "Lenovo's powerfull solution",
    },
    {
      _id: 4,
      name: "Sony Headset",
      slug: "sony-headset",
      category: "Headsets",
      image: "/images/sony-headset.jpg",
      price: 50,
      countInStock: 10,
      brand: "Sony",
      bewertungen: [
        { userId: 1, bewertung: 4 },
        { userId: 2, bewertung: 3 },
      ],
      rating: 4.8,
      numReviews: 33,
      description: "Listen your heart",
    },
    {
      _id: 5,
      name: "Everest Mouse",
      slug: "everest-mouse",
      category: "Mouses",
      image: "/images/everest-mouse.jpg",
      price: 10,
      countInStock: 50,
      brand: "Everest",
      bewertungen: [
        { userId: 1, bewertung: 4 },
        { userId: 2, bewertung: 3 },
      ],
      rating: 3.4,
      numReviews: 21,
      description: "Small usefull mouse",
    },
    {
      _id: 6,
      name: "Epson Printer",
      slug: "epson-printer",
      category: "Printers",
      image: "/images/epson-printer.jpg",
      price: 70,
      countInStock: 7,
      brand: "Epson",
      bewertungen: [
        { userId: 1, bewertung: 4 },
        { userId: 2, bewertung: 3 },
      ],
      rating: 2.1,
      numReviews: 8,
      description: "Prints your dream",
    },
  ],
};

export default data;
