import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Sevde",
      email: "svd@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Ömer",
      email: "ömer@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "Bekir",
      email: "bkr@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Terry Medhurst",
      email: "atuny0@sohu.com",
      password: bcrypt.hashSync("9uQFF1Lh"),
      isAdmin: false,
    },
    {
      name: "Sheldon Quigley",
      email: "hbingley1@plala.or.jp",
      password: bcrypt.hashSync("CQutx25i8r"),
      isAdmin: false,
    },
    {
      name: "Terrill Hills",
      email: "rshawe2@51.la",
      password: bcrypt.hashSync("OWsTbMUgFc"),
      isAdmin: false,
    },
    {
      name: "Miles Cummerata",
      email: "yraigatt3@nature.com",
      password: bcrypt.hashSync("sRQxjPfdS"),
      isAdmin: false,
    },
    {
      name: "Mavis Schultz",
      email: "kmeus4@upenn.edu",
      password: bcrypt.hashSync("aUTdmmmbH"),
      isAdmin: false,
    },
    {
      name: "Alison Reichert",
      email: "jtreleven5@nhs.uk",
      password: bcrypt.hashSync("zY1nE46Zm"),
      isAdmin: false,
    },
    {
      name: "Oleta Abbott",
      email: "dpettegre6@columbia.edu",
      password: bcrypt.hashSync("YVmhktgYVS"),
      isAdmin: false,
    },
    {
      name: "Ewell Mueller",
      email: "ggude7@chron.com",
      password: bcrypt.hashSync("MWwlaeWcOoF6"),
      isAdmin: false,
    },
    {
      name: "Demetrius Corkery",
      email: "nloiterton8@aol.com",
      password: bcrypt.hashSync("HTQxxXV9Bq4"),
      isAdmin: false,
    },
    {
      name: "Eleanora Price",
      email: "umcgourty9@jalbum.net",
      password: bcrypt.hashSync("i0xzpX"),
      isAdmin: false,
    },
    {
      name: "Marcel Jones",
      email: "acharlota@liveinternet.ru",
      password: bcrypt.hashSync("M9lbMdydMN"),
      isAdmin: false,
    },
    {
      name: "Assunta Rath",
      email: "rhallawellb@dropbox.com",
      password: bcrypt.hashSync("esTkitT1r"),
      isAdmin: false,
    },
    {
      name: "Trace Douglas",
      email: "lgribbinc@posterous.com",
      password: bcrypt.hashSync("ftGj8LZTtv9g"),
      isAdmin: false,
    },
    {
      name: "Enoch Lynch",
      email: "mturleyd@tumblr.com",
      password: bcrypt.hashSync("GyLnCB8gNIp"),
      isAdmin: false,
    },
    {
      name: "Jeanne Halvorson",
      email: "kminchelle@qq.com",
      password: bcrypt.hashSync("0lelplR"),
      isAdmin: false,
    },
    {
      name: "Trycia Fadel",
      email: "dpierrof@vimeo.com",
      password: bcrypt.hashSync("Vru55Y4tufI4"),
      isAdmin: false,
    },
    {
      name: "Bradford Prohaska",
      email: "vcholdcroftg@ucoz.com",
      password: bcrypt.hashSync("mSPzYZfR"),
      isAdmin: false,
    },
    {
      name: "Arely Skiles",
      email: "sberminghamh@chron.com",
      password: bcrypt.hashSync("cAjfb8vg"),
      isAdmin: false,
    },
    {
      name: "Gust Purdy",
      email: "bleveragei@so-net.ne.jp",
      password: bcrypt.hashSync("UZGAiqPqWQHQ"),
      isAdmin: false,
    },
    {
      name: "Lenna Renner",
      email: "aeatockj@psu.edu",
      password: bcrypt.hashSync("szWAG6hc"),
      isAdmin: false,
    },
    {
      name: "Doyle Ernser",
      email: "ckensleyk@pen.io",
      password: bcrypt.hashSync("tq7kPXyf"),
      isAdmin: false,
    },
    {
      name: "Tressa Weber",
      email: "froachel@howstuffworks.com",
      password: bcrypt.hashSync("rfVSKImC"),
      isAdmin: false,
    },
    {
      name: "Felicity O'Reilly",
      email: "beykelhofm@wikispaces.com",
      password: bcrypt.hashSync("zQwaHTHbuZyr"),
      isAdmin: false,
    },
    {
      name: "Jocelyn Schuster",
      email: "brickeardn@fema.gov",
      password: bcrypt.hashSync("bMQnPttV"),
      isAdmin: false,
    },
    {
      name: "Edwina Ernser",
      email: "dfundello@amazon.co.jp",
      password: bcrypt.hashSync("k9zgV68UKw8m"),
      isAdmin: false,
    },
    {
      name: "Griffin Braun",
      email: "lgronaverp@cornell.edu",
      password: bcrypt.hashSync("4a1dAKDv9KB9"),
      isAdmin: false,
    },
    {
      name: "Piper Schowalter",
      email: "fokillq@amazon.co.jp",
      password: bcrypt.hashSync("xZnWSWnqH"),
      isAdmin: false,
    },
    {
      name: "Kody Terry",
      email: "xisherwoodr@ask.com",
      password: bcrypt.hashSync("HLDqN5vCF"),
      isAdmin: false,
    },
    {
      name: "Macy Greenfelder",
      email: "jissetts@hostgator.com",
      password: bcrypt.hashSync("ePawWgrnZR8L"),
      isAdmin: false,
    },
    {
      name: "Maurine Stracke",
      email: "kdulyt@umich.edu",
      password: bcrypt.hashSync("5t6q4KC7O"),
      isAdmin: false,
    },
    {
      name: "Luciano Sauer",
      email: "smargiottau@altervista.org",
      password: bcrypt.hashSync("pSGvhgS2A"),
      isAdmin: false,
    },
    {
      name: "Kaya Emard",
      email: "lskeelv@webeden.co.uk",
      password: bcrypt.hashSync("Eolj9Svg28"),
      isAdmin: false,
    },
    {
      name: "Lee Schmidt",
      email: "gsilcockw@infoseek.co.jp",
      password: bcrypt.hashSync("AI6RmBSXjw2S"),
      isAdmin: false,
    },
    {
      name: "Darien Witting",
      email: "aaughtonx@businessweek.com",
      password: bcrypt.hashSync("Vzwc72RhNGu"),
      isAdmin: false,
    },
    {
      name: "Jacklyn Schimmel",
      email: "mbrooksbanky@gnu.org",
      password: bcrypt.hashSync("9V8lqrkq"),
      isAdmin: false,
    },
    {
      name: "Angelica Baumbach",
      email: "dalmondz@joomla.org",
      password: bcrypt.hashSync("wM5tOHRMQt6g"),
      isAdmin: false,
    },
    {
      name: "Delfina Ziemann",
      email: "nwytchard10@blogspot.com",
      password: bcrypt.hashSync("ij8mFevk"),
      isAdmin: false,
    },
    {
      name: "Thaddeus McCullough",
      email: "igannan11@microsoft.com",
      password: bcrypt.hashSync("MB63jkg3W"),
      isAdmin: false,
    },
    {
      name: "Salvatore Fisher",
      email: "lgherardi12@washington.edu",
      password: bcrypt.hashSync("m0eNOs"),
      isAdmin: false,
    },
    {
      name: "Jasmin Hermiston",
      email: "lgutridge13@sun.com",
      password: bcrypt.hashSync("SqR03CE"),
      isAdmin: false,
    },
    {
      name: "Nicklaus Cruickshank",
      email: "cslateford14@blogspot.com",
      password: bcrypt.hashSync("wpbWfIbpIgGc"),
      isAdmin: false,
    },
    {
      name: "Tiara Rolfson",
      email: "mhaslegrave15@springer.com",
      password: bcrypt.hashSync("sq5FYgvU"),
      isAdmin: false,
    },
    {
      name: "Garret Klocko",
      email: "kbrecknock16@marriott.com",
      password: bcrypt.hashSync("KoNiIBiHE"),
      isAdmin: false,
    },
    {
      name: "Reginald Wisoky",
      email: "rlaxe17@tamu.edu",
      password: bcrypt.hashSync("OHFibd"),
      isAdmin: false,
    },
    {
      name: "Humberto Botsford",
      email: "pidill18@china.com.cn",
      password: bcrypt.hashSync("GbBDdjbKG1a2"),
      isAdmin: false,
    },
    {
      name: "Justus Sipes",
      email: "rmcritchie19@topsy.com",
      password: bcrypt.hashSync("QFSwkjeVEhOQ"),
      isAdmin: false,
    },
    {
      name: "Coralie Boyle",
      email: "rlangston1a@51.la",
      password: bcrypt.hashSync("rU8ybew"),
      isAdmin: false,
    },
    {
      name: "Felicita Gibson",
      email: "jevanson1b@admin.ch",
      password: bcrypt.hashSync("1Dlvqluwi5zO"),
      isAdmin: false,
    },
    {
      name: "Pearl Blick",
      email: "ssarjant1c@statcounter.com",
      password: bcrypt.hashSync("y2YBSxtcmXVW"),
      isAdmin: false,
    },
    {
      name: "Johnathon Predovic",
      email: "xlinster1d@bravesites.com",
      password: bcrypt.hashSync("WHAE1AtmDh"),
      isAdmin: false,
    },
    {
      name: "Jerry Kertzmann",
      email: "tmullender1e@scientificamerican.com",
      password: bcrypt.hashSync("fxJRvUVCFA95"),
      isAdmin: false,
    },
    {
      name: "Elbert Gottlieb",
      email: "gmein1f@nasa.gov",
      password: bcrypt.hashSync("VYaG1Ew"),
      isAdmin: false,
    },
    {
      name: "Sincere Mueller",
      email: "gmaccumeskey1g@buzzfeed.com",
      password: bcrypt.hashSync("bETj6uCOI"),
      isAdmin: false,
    },
    {
      name: "Telly Spinka",
      email: "bpetts1h@smugmug.com",
      password: bcrypt.hashSync("IxI5sjpNT5F"),
      isAdmin: false,
    },
    {
      name: "Hal Keebler",
      email: "ajozef1i@usatoday.com",
      password: bcrypt.hashSync("uAVFvWB0Pxi"),
      isAdmin: false,
    },
    {
      name: "Megane Armstrong",
      email: "oyakushkev1j@oracle.com",
      password: bcrypt.hashSync("UB3BAOn8Sj7"),
      isAdmin: false,
    },
    {
      name: "Toy Olson",
      email: "bpickering1k@clickbank.net",
      password: bcrypt.hashSync("J4f0Es7sxXVO"),
      isAdmin: false,
    },
    {
      name: "Deanna Glover",
      email: "nworley1l@thetimes.co.uk",
      password: bcrypt.hashSync("HhWAr5TR"),
      isAdmin: false,
    },
    {
      name: "Marcella Shanahan",
      email: "klife1m@i2i.jp",
      password: bcrypt.hashSync("ZdEndJIQLM"),
      isAdmin: false,
    },
    {
      name: "Rachel Jacobson",
      email: "dlambarth1n@blinklist.com",
      password: bcrypt.hashSync("1zosSj9eR"),
      isAdmin: false,
    },
    {
      name: "Nora Sawayn",
      email: "cepgrave1o@biblegateway.com",
      password: bcrypt.hashSync("BnC5P3MdJ"),
      isAdmin: false,
    },
    {
      name: "Mozell O'Connell",
      email: "mpoyner1p@google.co.uk",
      password: bcrypt.hashSync("nCTH1QhLCNY"),
      isAdmin: false,
    },
    {
      name: "Nasir Leuschke",
      email: "eburras1q@go.com",
      password: bcrypt.hashSync("Y7UmdaATt"),
      isAdmin: false,
    },
    {
      name: "Quinn Witting",
      email: "gfernandes1r@virginia.edu",
      password: bcrypt.hashSync("LzI2Plmj"),
      isAdmin: false,
    },
    {
      name: "Jeanne O'Keefe",
      email: "hollet1s@trellian.com",
      password: bcrypt.hashSync("WK46QB"),
      isAdmin: false,
    },
    {
      name: "Terrence Koelpin",
      email: "hfasey1t@home.pl",
      password: bcrypt.hashSync("vDMcOSFj0"),
      isAdmin: false,
    },
    {
      name: "Davonte Heaney",
      email: "gbarhams1u@cnet.com",
      password: bcrypt.hashSync("uDO326b3Hn7O"),
      isAdmin: false,
    },
    {
      name: "Everette Prohaska",
      email: "rstrettle1v@globo.com",
      password: bcrypt.hashSync("ryhdXB"),
      isAdmin: false,
    },
    {
      name: "Oda Schmidt",
      email: "btegler1w@elegantthemes.com",
      password: bcrypt.hashSync("xx9O9fzZI"),
      isAdmin: false,
    },
    {
      name: "Twila Padberg",
      email: "cmasurel1x@baidu.com",
      password: bcrypt.hashSync("es8eVhVy4c"),
      isAdmin: false,
    },
    {
      name: "Amelia Mann",
      email: "omarsland1y@washingtonpost.com",
      password: bcrypt.hashSync("MT463NsEI"),
      isAdmin: false,
    },
    {
      name: "Frederique Boehm",
      email: "mcrumpe1z@techcrunch.com",
      password: bcrypt.hashSync("F8JxU31tNw"),
      isAdmin: false,
    },
    {
      name: "Clotilde Larson",
      email: "wfeldon20@netlog.com",
      password: bcrypt.hashSync("cLcJUmA"),
      isAdmin: false,
    },
    {
      name: "Moriah Mills",
      email: "ahinckes21@google.es",
      password: bcrypt.hashSync("dIoZ2huN"),
      isAdmin: false,
    },
    {
      name: "Claudia Dooley",
      email: "ptilson22@360.cn",
      password: bcrypt.hashSync("jNbmsr"),
      isAdmin: false,
    },
    {
      name: "Deon Gutkowski",
      email: "cgaber23@prlog.org",
      password: bcrypt.hashSync("nieEPfUI"),
      isAdmin: false,
    },
    {
      name: "Amos Weimann",
      email: "rkingswood24@usa.gov",
      password: bcrypt.hashSync("0VNksmUL7"),
      isAdmin: false,
    },
    {
      name: "Frankie Hudson",
      email: "dbuist25@hao123.com",
      password: bcrypt.hashSync("OlP0CIw"),
      isAdmin: false,
    },
    {
      name: "Harrison Lemke",
      email: "pmoraleda26@symantec.com",
      password: bcrypt.hashSync("QrZGjkTF8eX"),
      isAdmin: false,
    },
    {
      name: "Guy Franecki",
      email: "vkohrt27@hostgator.com",
      password: bcrypt.hashSync("yMmUuTZDdPC"),
      isAdmin: false,
    },
    {
      name: "Sidney Rutherford",
      email: "capplewhite28@nationalgeographic.com",
      password: bcrypt.hashSync("oqqDPsff"),
      isAdmin: false,
    },
    {
      name: "Maymie Yundt",
      email: "kogilvy29@blogtalkradio.com",
      password: bcrypt.hashSync("aGX6R9Xd9bd2"),
      isAdmin: false,
    },
    {
      name: "Rita Shields",
      email: "gconford2a@wordpress.com",
      password: bcrypt.hashSync("CNZ3xN"),
      isAdmin: false,
    },
    {
      name: "Aniya Wisozk",
      email: "dmantle2b@reuters.com",
      password: bcrypt.hashSync("SBnr789"),
      isAdmin: false,
    },
    {
      name: "Angelica Metz",
      email: "kpondjones2c@nsw.gov.au",
      password: bcrypt.hashSync("H4IiV9f8jb"),
      isAdmin: false,
    },
    {
      name: "Rupert Upton",
      email: "whuman2d@hp.com",
      password: bcrypt.hashSync("JyHAUcC"),
      isAdmin: false,
    },
    {
      name: "Eleazar Torp",
      email: "fschlagman2e@deliciousdays.com",
      password: bcrypt.hashSync("icEdQz4YnwV"),
      isAdmin: false,
    },
    {
      name: "Anais Yundt",
      email: "agreenhouse2f@mashable.com",
      password: bcrypt.hashSync("VmqqWniF"),
      isAdmin: false,
    },
    {
      name: "Gayle Krajcik",
      email: "cdwyr2g@shop-pro.jp",
      password: bcrypt.hashSync("x96XD8Fm"),
      isAdmin: false,
    },
    {
      name: "Wilma Hickle",
      email: "omottley2h@hugedomains.com",
      password: bcrypt.hashSync("67oJrJe6ta"),
      isAdmin: false,
    },
    {
      name: "Arne Jacobs",
      email: "hyaknov2i@hhs.gov",
      password: bcrypt.hashSync("Xw8nIye1"),
      isAdmin: false,
    },
    {
      name: "Emely Schmitt",
      email: "clambol2j@bloglovin.com",
      password: bcrypt.hashSync("MJRFJutRGS"),
      isAdmin: false,
    },
    {
      name: "Fabiola Oberbrunner",
      email: "dduggan2k@simplemachines.org",
      password: bcrypt.hashSync("Hf0TgLPXG"),
      isAdmin: false,
    },
    {
      name: "Kari Schinner",
      email: "jtossell2l@drupal.org",
      password: bcrypt.hashSync("LTRc4mC"),
      isAdmin: false,
    },
    {
      name: "Rory Conn",
      email: "cchomiszewski2m@cbsnews.com",
      password: bcrypt.hashSync("xjuQsRDR0NP6"),
      isAdmin: false,
    },
    {
      name: "Cristobal Watsica",
      email: "bgoby2n@washingtonpost.com",
      password: bcrypt.hashSync("aKzuEqfI3wU"),
      isAdmin: false,
    },
    {
      name: "Allene Harber",
      email: "cdavydochkin2o@globo.com",
      password: bcrypt.hashSync("N1node"),
      isAdmin: false,
    },
    {
      name: "Lempi Runte",
      email: "zstenning2p@list-manage.com",
      password: bcrypt.hashSync("Ck5jBaO6691g"),
      isAdmin: false,
    },
    {
      name: "Terrell Schuppe",
      email: "flesslie2q@google.nl",
      password: bcrypt.hashSync("XUKU613LscMS"),
      isAdmin: false,
    },
    {
      name: "Tevin Prohaska",
      email: "pcumbes2r@networkadvertising.org",
      password: bcrypt.hashSync("obhSsvCF8c0"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "HP Curved Monitor",
      slug: "hp-curved-monitor",
      category: "Monitors",
      image: "/images/monitor1.jpg",
      images: ["/images/monitor1.jpg", "/images/monitor2.jpg"],
      price: 150,
      countInStock: 10,
      brand: "HP",
      rating: 3.5,
      numReviews: 43,
      reviews: [{ name: "Ömer", comment: "sehr cool..", rating: 5 }],
      description: "Eye-friendly Monitor",
    },
    {
      name: "Microsoft Wireless Keyboard",
      slug: "microsoft-wireless-keyboard",
      category: "Keyboards",
      image: "/images/keyboard1.jpg",
      price: 30,
      countInStock: 20,
      brand: "Microsoft",
      rating: 2.1,
      numReviews: 7,
      description: "Keyboard without cable",
      reviews: [{ name: "Ömer", comment: "sehr cool..", rating: 5 }],
    },
    {
      name: "Thinkpad Laptop",
      slug: "thinkpad-laptop",
      category: "Laptops",
      image: "/images/lenovo-laptop1.jpg",
      price: 750,
      countInStock: 1,
      brand: "Lenovo",

      rating: 2.4,
      numReviews: 1,
      description: "Lenovo's powerfull solution",
      reviews: [{ name: "Ömer", comment: "sehr cool..", rating: 5 }],
    },
    {
      name: "Sony Headset",
      slug: "sony-headset",
      category: "Headsets",
      image: "/images/sony-headset.jpg",
      price: 50,
      countInStock: 10,
      brand: "Sony",

      rating: 4.8,
      numReviews: 33,
      description: "Listen your heart",
      reviews: [{ name: "Ömer", comment: "sehr cool..", rating: 5 }],
    },
    {
      name: "Everest Mouse",
      slug: "everest-mouse",
      category: "Mouses",
      image: "/images/everest-mouse.jpg",
      price: 10,
      countInStock: 50,
      brand: "Everest",

      rating: 3.4,
      numReviews: 21,
      description: "Small usefull mouse",
      reviews: [{ name: "Ömer", comment: "sehr cool..", rating: 5 }],
    },
    {
      name: "Epson Printer",
      slug: "epson-printer",
      category: "Printers",
      image: "/images/epson-printer.jpg",
      price: 70,
      countInStock: 7,
      brand: "Epson",

      rating: 2.1,
      numReviews: 8,
      description: "Prints your dream",
      reviews: [{ name: "Ömer", comment: "sehr cool..", rating: 5 }],
    },
  ],
};
export default data;
