@API_URL = http://localhost:3484

### PRODUCTS ROUTE
GET {{API_URL}}/api/products

### PRODUCTID ROUTE
GET {{API_URL}}/api/products/63280ac3ac92d3452f5e161c

### CATEGORIES ROUTE
GET {{API_URL}}/api/products/categories

### CATEGORIES ROUTE
GET {{API_URL}}/api/products/categories



